name: java ci with maven and cache
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
    - uses: actions/checkout@v3
    - name: setup jdk 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Cache maven dependencies
    - uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-cache
    - name: build with maven
      run: mvn -B package --file pom.xml
   
   
 
          
  
