name: install jdk with maven and cache
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
    - uses: actions/checkout@v3
    - name: setup jdk 11
    - uses: actions/setup-java@v4.0.0
      with:
        java-version: '11'
        distribution: 'jdk'
        cache: maven
    - name: Cache
    - uses: actions/cache@v4.0.0
      with:
        path: ~/.m2
        key: ${{ runner.os }}-cache
    - name: build with maven
      run: mvn -B package --file pom.xml
   
   
 
          
  
