name: trigger action
on: 
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
      branches:
       - master
       - 'releases/**'
jobs: 
 basic-trigger-action:
   runs-on: ubuntu-latest 
   steps:  
     - name: print msg 
       run: echo "trigger action"
  
